export { default as Whatsapp } from './Whatsapp'
export { default as Banner } from './Banner'
export { default as Investment } from './Investment'
export { default as Footer } from './Footer'
export { default as Feedbacks } from './Feedbacks'
export { default as Budget } from './Budget'
